// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyConETAxs91Ejpe8SsvVBoaM_5CdDXj6T0',
    appId: '1:894916493246:web:a178ef3f3e10c8749a43ef',
    messagingSenderId: '894916493246',
    projectId: 'expt6-865f9',
    authDomain: 'expt6-865f9.firebaseapp.com',
    storageBucket: 'expt6-865f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgaoiQkCap4ScBpZ2zHAjpoRybQtFW2iI',
    appId: '1:894916493246:android:7b9838e5dae3b52e9a43ef',
    messagingSenderId: '894916493246',
    projectId: 'expt6-865f9',
    storageBucket: 'expt6-865f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkbfh3IE8B8fOcTAqYJL2TLfHUwTmGKck',
    appId: '1:894916493246:ios:37cb11448d6ba35c9a43ef',
    messagingSenderId: '894916493246',
    projectId: 'expt6-865f9',
    storageBucket: 'expt6-865f9.appspot.com',
    iosBundleId: 'com.example.expt6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkbfh3IE8B8fOcTAqYJL2TLfHUwTmGKck',
    appId: '1:894916493246:ios:666c19b85b1cb8009a43ef',
    messagingSenderId: '894916493246',
    projectId: 'expt6-865f9',
    storageBucket: 'expt6-865f9.appspot.com',
    iosBundleId: 'com.example.expt6.RunnerTests',
  );
}
